CREATE TABLE IF NOT EXISTS MS_CONFIG (
APPLICATION VARCHAR(255) NOT NULL,
PROFILE VARCHAR(255) NOT NULL,
CONFIG_LABEL VARCHAR(255) NOT NULL,
PROP_KEY VARCHAR(255) NOT NULL,
VALUE VARCHAR NOT NULL,
CONSTRAINT MS_CONFIG_PK PRIMARY KEY(APPLICATION,PROFILE,CONFIG_LABEL,PROP_KEY)
);